[package]
name = "valihuutobot-v2"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
reqwest = { version = "0.12.1", features = ["blocking"] }
rss = "2.0.11"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
urlencoding = "2.1.3"
